export type LabDataMetrics = "cumulativeLayoutShift"
  | "firstContentfulPaint"
  | "firstContentfulPaint3g"
  | "speedIndex"
  | "timeToInteractive"
  | "totalBlockingTime"
  | "networkRtt"
  | "totalByteWeight"
  | "timeToFirstByte"
  | "firstMeaningfulPaint";
