export type RuntimePerfMetricsModel = "jSEventListeners"
  | "nodes"
  | "layoutCount"
  | "recalcStyleCount"
  | "layoutDuration"
  | "recalcStyleDuration"
  | "scriptDuration"
  | "taskDuration"
  | "jSHeapUsedSize"
  | "jSHeapTotalSize";